'use client'

import { useEffect, useMemo, useState } from 'react'
import { BarChart3, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, Circle, ClipboardList, Clock3, Ellipsis, Filter, LayoutDashboard, ListTodo, Menu, Moon, MoreHorizontal, Plus, Search, Settings, Sun, Target, Trash2, TrendingUp, X } from 'lucide-react'

type Status = 'Pending' | 'In Progress' | 'Completed'
type Priority = 'Low' | 'Medium' | 'High'
type Category = 'Study' | 'Work' | 'Personal' | 'Other'
type Task = { id: string; title: string; description: string; dueDate: string; priority: Priority; category: Category; status: Status }

const today = new Date()
const iso = (d: Date) => d.toISOString().slice(0, 10)
const dateLabel = (value: string) => new Date(`${value}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
const starterTasks: Task[] = [
  { id: '1', title: 'Review lecture notes', description: 'Consolidate notes from this week\'s sessions.', dueDate: iso(today), priority: 'High', category: 'Study', status: 'In Progress' },
  { id: '2', title: 'Submit research proposal', description: 'Final pass and upload to the student portal.', dueDate: iso(new Date(today.getTime() + 86400000)), priority: 'High', category: 'Study', status: 'Pending' },
  { id: '3', title: 'Plan weekend groceries', description: 'Make a list of essentials for the week.', dueDate: iso(new Date(today.getTime() + 2 * 86400000)), priority: 'Low', category: 'Personal', status: 'Pending' },
  { id: '4', title: 'Team stand-up notes', description: 'Share the recap with the project group.', dueDate: iso(new Date(today.getTime() - 86400000)), priority: 'Medium', category: 'Work', status: 'Completed' },
  { id: '5', title: 'Practice presentation', description: 'Run through the opening and key slides.', dueDate: iso(new Date(today.getTime() + 4 * 86400000)), priority: 'Medium', category: 'Work', status: 'Pending' },
  { id: '6', title: 'Read 20 pages', description: 'Continue the personal development book.', dueDate: iso(new Date(today.getTime() - 2 * 86400000)), priority: 'Low', category: 'Personal', status: 'Completed' },
]

function StatCard({ label, value, note, icon: Icon, tone }: { label: string; value: string | number; note: string; icon: typeof CheckCircle2; tone: string }) {
  return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon /></div><div><p className="eyebrow">{label}</p><p className="stat-value">{value}</p><p className="stat-note">{note}</p></div></div>
}

export default function Page() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [view, setView] = useState<'Dashboard' | 'Tasks' | 'Calendar' | 'Statistics' | 'Settings'>('Dashboard')
  const [dark, setDark] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const [query, setQuery] = useState('')
  const [statusFilter, setStatusFilter] = useState('All status')
  const [priorityFilter, setPriorityFilter] = useState('All priorities')
  const [categoryFilter, setCategoryFilter] = useState('All categories')
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1))
  const [selectedDate, setSelectedDate] = useState(iso(today))
  const [modal, setModal] = useState(false)
  const [editing, setEditing] = useState<Task | null>(null)

  useEffect(() => { const raw = localStorage.getItem('taskflow-tasks'); setTasks(raw ? JSON.parse(raw) : starterTasks); setDark(localStorage.getItem('taskflow-theme') === 'dark') }, [])
  useEffect(() => { if (tasks.length) localStorage.setItem('taskflow-tasks', JSON.stringify(tasks)) }, [tasks])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('taskflow-theme', dark ? 'dark' : 'light') }, [dark])

  const completed = tasks.filter(t => t.status === 'Completed').length
  const pending = tasks.filter(t => t.status !== 'Completed').length
  const overdue = tasks.filter(t => t.status !== 'Completed' && t.dueDate < iso(today)).length
  const progress = tasks.length ? Math.round(completed / tasks.length * 100) : 0
  const filtered = useMemo(() => tasks.filter(t => (!query || `${t.title} ${t.description}`.toLowerCase().includes(query.toLowerCase())) && (statusFilter === 'All status' || t.status === statusFilter) && (priorityFilter === 'All priorities' || t.priority === priorityFilter) && (categoryFilter === 'All categories' || t.category === categoryFilter)), [tasks, query, statusFilter, priorityFilter, categoryFilter])
  const upcoming = tasks.filter(t => t.status !== 'Completed').sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 4)
  const todayTasks = tasks.filter(t => t.dueDate === iso(today))
  const toggleTask = (id: string) => setTasks(ts => ts.map(t => t.id === id ? { ...t, status: t.status === 'Completed' ? 'Pending' : 'Completed' } : t))
  const removeTask = (id: string) => setTasks(ts => ts.filter(t => t.id !== id))

  function openAdd() { setEditing(null); setModal(true) }
  function saveTask(task: Task) { setTasks(ts => editing ? ts.map(t => t.id === editing.id ? task : t) : [task, ...ts]); setModal(false) }

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}>
      <div className="brand"><span className="brand-mark"><Check /></span><span>TaskFlow</span></div>
      <div className="workspace"><span className="avatar">JD</span><div><strong>Jordan Davis</strong><small>Personal workspace</small></div><MoreHorizontal className="muted-icon" /></div>
      <nav><p className="nav-label">Workspace</p>{[['Dashboard', LayoutDashboard], ['Tasks', ListTodo], ['Calendar', CalendarDays], ['Statistics', BarChart3]].map(([name, Icon]) => <button key={name as string} className={view === name ? 'active' : ''} onClick={() => { setView(name as any); setMobileNav(false) }}><Icon />{name as string}{name === 'Tasks' && <span className="nav-count">{pending}</span>}</button>)}<p className="nav-label nav-space">Preferences</p><button className={view === 'Settings' ? 'active' : ''} onClick={() => { setView('Settings'); setMobileNav(false) }}><Settings />Settings</button></nav>
      <div className="sidebar-bottom"><div className="focus-card"><Target /><div><strong>Stay focused</strong><span>{progress}% of your tasks complete</span></div></div><button className="theme-toggle" onClick={() => setDark(!dark)}>{dark ? <Sun /> : <Moon />} {dark ? 'Light mode' : 'Dark mode'}</button></div>
    </aside>
    {mobileNav && <button className="scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
    <main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div className="breadcrumb">Workspace <span>/</span> <strong>{view}</strong></div><div className="top-actions"><button className="icon-button"><Search /></button><button className="avatar top-avatar">JD</button></div></header>
      <div className="content-wrap">{view === 'Dashboard' && <Dashboard onAdd={openAdd} tasks={tasks} todayTasks={todayTasks} upcoming={upcoming} completed={completed} pending={pending} overdue={overdue} progress={progress} toggleTask={toggleTask} setView={setView} />}{view === 'Tasks' && <TasksPage tasks={filtered} query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} priority={priorityFilter} setPriority={setPriorityFilter} category={categoryFilter} setCategory={setCategoryFilter} onAdd={openAdd} toggleTask={toggleTask} onEdit={(t) => { setEditing(t); setModal(true) }} onDelete={removeTask} />}{view === 'Calendar' && <CalendarPage month={month} setMonth={setMonth} selected={selectedDate} setSelected={setSelectedDate} tasks={tasks} />}{view === 'Statistics' && <StatsPage tasks={tasks} progress={progress} />}{view === 'Settings' && <SettingsPage dark={dark} setDark={setDark} clear={() => { if (confirm('Clear all tasks?')) { setTasks([]); localStorage.removeItem('taskflow-tasks') } }} />}</div>
    </main>{modal && <TaskModal initial={editing} onClose={() => setModal(false)} onSave={saveTask} />}
  </div>
}

function PageHeading({ eyebrow, title, subtitle, action }: { eyebrow: string; title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow accent">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div>{action}</div> }
function Dashboard({ onAdd, tasks, todayTasks, upcoming, completed, pending, overdue, progress, toggleTask, setView }: any) { return <><PageHeading eyebrow="Overview" title="Good morning, Jordan" subtitle={`${today.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })} · Make today count.`} action={<button className="primary-button" onClick={onAdd}><Plus /> Add task</button>} /><div className="stats-grid"><StatCard label="Total tasks" value={tasks.length} note="All your tasks" icon={ClipboardList} tone="blue" /><StatCard label="Completed" value={completed} note={`${progress}% completion rate`} icon={CheckCircle2} tone="green" /><StatCard label="In progress" value={pending} note="Keep the momentum" icon={Clock3} tone="orange" /><StatCard label="Overdue" value={overdue} note={overdue ? 'Needs your attention' : 'You are all caught up'} icon={TrendingUp} tone="rose" /></div><div className="dashboard-grid"><section className="panel today-panel"><div className="panel-heading"><div><h2>Today&apos;s focus</h2><p>Tasks scheduled for today</p></div><button className="text-button" onClick={() => setView('Tasks')}>View all <ChevronRight /></button></div>{todayTasks.length ? todayTasks.map((t: Task) => <TaskRow key={t.id} task={t} toggle={toggleTask} />) : <Empty text="No tasks scheduled for today." />}</section><section className="panel progress-panel"><div className="panel-heading"><div><h2>Weekly progress</h2><p>Your productivity at a glance</p></div><BarChart3 className="panel-icon" /></div><div className="progress-circle" style={{ '--progress': `${progress * 3.6}deg` } as React.CSSProperties}><div><strong>{progress}%</strong><span>complete</span></div></div><div className="week-bars">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day, i) => <div key={day}><div className="bar-track"><i style={{ height: `${[58, 74, 43, 82, 68, 35, 54][i]}%` }} /></div><span>{day}</span></div>)}</div></section><section className="panel deadline-panel"><div className="panel-heading"><div><h2>Upcoming deadlines</h2><p>What&apos;s coming up next</p></div><button className="text-button" onClick={() => setView('Calendar')}>Calendar <ChevronRight /></button></div>{upcoming.length ? upcoming.map((t: Task) => <div className="deadline-row" key={t.id}><div className="date-tile"><strong>{new Date(`${t.dueDate}T12:00:00`).getDate()}</strong><span>{new Date(`${t.dueDate}T12:00:00`).toLocaleDateString('en-US', { month: 'short' })}</span></div><div className="deadline-info"><strong>{t.title}</strong><span>{t.category} · {t.priority} priority</span></div><span className={`priority-dot ${t.priority.toLowerCase()}`} /></div>) : <Empty text="No upcoming deadlines." />}</section></div></> }
function TaskRow({ task, toggle }: { task: Task; toggle: (id: string) => void }) { return <div className="task-row"><button className={`check-button ${task.status === 'Completed' ? 'checked' : ''}`} onClick={() => toggle(task.id)} aria-label={`Mark ${task.title} complete`}>{task.status === 'Completed' && <Check />}</button><div className={task.status === 'Completed' ? 'task-copy done' : 'task-copy'}><strong>{task.title}</strong><span>{task.description}</span></div><Badge label={task.category} /><span className={`priority-text ${task.priority.toLowerCase()}`}>{task.priority}</span><button className="more-button"><Ellipsis /></button></div> }
function Badge({ label }: { label: string }) { return <span className={`badge ${label.toLowerCase()}`}>{label}</span> }
function Empty({ text }: { text: string }) { return <div className="empty"><Circle /><p>{text}</p></div> }

function TasksPage({ tasks, query, setQuery, status, setStatus, priority, setPriority, category, setCategory, onAdd, toggleTask, onEdit, onDelete }: any) { return <><PageHeading eyebrow="Manage your work" title="All tasks" subtitle="Keep everything organized and moving forward." action={<button className="primary-button" onClick={onAdd}><Plus /> Add task</button>} /><div className="task-toolbar"><div className="search-field"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tasks..." /></div><select value={status} onChange={e => setStatus(e.target.value)}><option>All status</option><option>Pending</option><option>In Progress</option><option>Completed</option></select><select value={priority} onChange={e => setPriority(e.target.value)}><option>All priorities</option><option>Low</option><option>Medium</option><option>High</option></select><select value={category} onChange={e => setCategory(e.target.value)}><option>All categories</option><option>Study</option><option>Work</option><option>Personal</option><option>Other</option></select><Filter className="filter-icon" /></div><section className="panel task-list-panel"><div className="list-header"><span>{tasks.length} tasks</span><span>Due date</span><span>Priority</span><span>Status</span><span /></div>{tasks.length ? tasks.map((t: Task) => <div className="task-list-row" key={t.id}><button className={`check-button ${t.status === 'Completed' ? 'checked' : ''}`} onClick={() => toggleTask(t.id)} aria-label={`Complete ${t.title}`}>{t.status === 'Completed' && <Check />}</button><div className="task-copy"><strong className={t.status === 'Completed' ? 'strike' : ''}>{t.title}</strong><span>{t.description}</span><Badge label={t.category} /></div><span className="due-date">{dateLabel(t.dueDate)}</span><span className={`priority-text ${t.priority.toLowerCase()}`}>{t.priority}</span><span className={`status-pill ${t.status.toLowerCase().replace(' ', '-')}`}>{t.status}</span><div className="row-actions"><button onClick={() => onEdit(t)} aria-label="Edit task"><Settings /></button><button onClick={() => onDelete(t.id)} aria-label="Delete task"><Trash2 /></button></div></div>) : <Empty text="No tasks match your filters." />}</section></> }

function CalendarPage({ month, setMonth, selected, setSelected, tasks }: any) { const year = month.getFullYear(), mon = month.getMonth(), first = new Date(year, mon, 1).getDay(), days = new Date(year, mon + 1, 0).getDate(); const cells = Array.from({ length: first + days }, (_, i) => i < first ? null : i - first + 1); const selectedTasks = tasks.filter((t: Task) => t.dueDate === selected); return <><PageHeading eyebrow="Plan ahead" title="Calendar" subtitle="See your deadlines and plan your week with intention." /><section className="calendar-layout"><div className="panel calendar-panel"><div className="calendar-head"><button className="icon-button" onClick={() => setMonth(new Date(year, mon - 1, 1))}><ChevronLeft /></button><h2>{month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h2><button className="icon-button" onClick={() => setMonth(new Date(year, mon + 1, 1))}><ChevronRight /></button></div><div className="calendar-grid weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((day, i) => { const key = day ? iso(new Date(year, mon, day)) : `empty-${i}`; const count = day ? tasks.filter((t: Task) => t.dueDate === key).length : 0; return <button key={key} className={`calendar-day ${key === iso(today) ? 'today' : ''} ${key === selected ? 'selected' : ''}`} disabled={!day} onClick={() => day && setSelected(key)}><span>{day}</span>{count > 0 && <i>{count}</i>}</button> })}</div></div><div className="panel selected-day"><div className="panel-heading"><div><p className="eyebrow accent">Selected date</p><h2>{new Date(`${selected}T12:00:00`).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</h2></div><CalendarDays className="panel-icon" /></div>{selectedTasks.length ? selectedTasks.map((t: Task) => <div className="mini-task" key={t.id}><span className={`priority-dot ${t.priority.toLowerCase()}`} /><div><strong>{t.title}</strong><span>{t.category} · {t.status}</span></div></div>) : <Empty text="No tasks for this date." />}</div></section></> }

function StatsPage({ tasks, progress }: any) { const categories = ['Study','Work','Personal','Other']; const priorities = ['High','Medium','Low']; return <><PageHeading eyebrow="Your rhythm" title="Statistics" subtitle="Understand your habits and make progress visible." /><div className="stats-grid"><StatCard label="Completion rate" value={`${progress}%`} note="Across all tasks" icon={TrendingUp} tone="green" /><StatCard label="Total completed" value={tasks.filter((t: Task) => t.status === 'Completed').length} note="Tasks finished" icon={CheckCircle2} tone="blue" /><StatCard label="Current streak" value="4 days" note="Personal best: 12 days" icon={Target} tone="orange" /><StatCard label="Focus time" value="12.5h" note="This week" icon={Clock3} tone="rose" /></div><div className="analytics-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Weekly productivity</h2><p>Tasks completed each day</p></div><span className="chart-legend"><i /> Completed</span></div><div className="large-bars">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day, i) => <div key={day}><div className="large-bar-track"><i style={{ height: `${[35, 62, 48, 80, 58, 28, 45][i]}%` }}><b>{[2,4,3,5,4,1,3][i]}</b></i></div><span>{day}</span></div>)}</div></section><section className="panel breakdown-panel"><div className="panel-heading"><div><h2>By category</h2><p>Where your attention goes</p></div></div>{categories.map((c, i) => { const count = tasks.filter((t: Task) => t.category === c).length; return <div className="breakdown-row" key={c}><span>{c}</span><div className="breakdown-track"><i style={{ width: `${Math.max(8, count / Math.max(tasks.length, 1) * 100)}%` }} /></div><strong>{count}</strong></div> })}</section><section className="panel breakdown-panel"><div className="panel-heading"><div><h2>By priority</h2><p>How you&apos;re balancing urgency</p></div></div>{priorities.map((p) => { const count = tasks.filter((t: Task) => t.priority === p).length; return <div className="breakdown-row" key={p}><span>{p}</span><div className="breakdown-track"><i className={p.toLowerCase()} style={{ width: `${Math.max(8, count / Math.max(tasks.length, 1) * 100)}%` }} /></div><strong>{count}</strong></div> })}</section></div></> }

function SettingsPage({ dark, setDark, clear }: any) { return <><PageHeading eyebrow="Make it yours" title="Settings" subtitle="Tune TaskFlow to fit the way you work." /><div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><div><h2>Appearance</h2><p>Choose how TaskFlow looks on your device.</p></div><Sun className="panel-icon" /></div><div className="setting-row"><div><strong>Dark mode</strong><span>Use a darker color palette at night.</span></div><button className={`switch ${dark ? 'on' : ''}`} onClick={() => setDark(!dark)} aria-label="Toggle dark mode"><i /></button></div></section><section className="panel settings-panel danger-panel"><div className="panel-heading"><div><h2>Data management</h2><p>Manage the tasks stored locally in this browser.</p></div><Trash2 className="panel-icon" /></div><div className="setting-row"><div><strong>Clear all task data</strong><span>This permanently removes all saved tasks.</span></div><button className="outline-danger" onClick={clear}>Clear data</button></div></section><section className="panel settings-panel"><div className="panel-heading"><div><h2>About TaskFlow</h2><p>A calm, focused space for getting things done.</p></div></div><div className="about-line"><span>Version</span><strong>1.0.0</strong></div><div className="about-line"><span>Storage</span><strong>Local browser storage</strong></div></section></div></> }

function TaskModal({ initial, onClose, onSave }: { initial: Task | null; onClose: () => void; onSave: (task: Task) => void }) { const [title, setTitle] = useState(initial?.title || ''); const [description, setDescription] = useState(initial?.description || ''); const [dueDate, setDueDate] = useState(initial?.dueDate || iso(today)); const [priority, setPriority] = useState<Priority>(initial?.priority || 'Medium'); const [category, setCategory] = useState<Category>(initial?.category || 'Study'); const [status, setStatus] = useState<Status>(initial?.status || 'Pending'); return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><div className="modal"><div className="modal-head"><div><p className="eyebrow accent">Task details</p><h2>{initial ? 'Edit task' : 'Create a new task'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X /></button></div><label>Task title<input autoFocus value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Finish assignment" /></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Add a little context..." /></label><div className="form-grid"><label>Due date<input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} /></label><label>Priority<select value={priority} onChange={e => setPriority(e.target.value as Priority)}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Category<select value={category} onChange={e => setCategory(e.target.value as Category)}><option>Study</option><option>Work</option><option>Personal</option><option>Other</option></select></label><label>Status<select value={status} onChange={e => setStatus(e.target.value as Status)}><option>Pending</option><option>In Progress</option><option>Completed</option></select></label></div><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!title.trim()} onClick={() => onSave({ id: initial?.id || crypto.randomUUID(), title: title.trim(), description, dueDate, priority, category, status })}>{initial ? 'Save changes' : 'Create task'}</button></div></div></div> }
